  return {
--    'nvim-java/nvim-java',
    --config = function()
      --local jdtls = require('lspconfig').jdtls
      --local home = os.getenv('HOME')
      --local lombok_path = home .. "/tools/lombok.jar"
      --local equinox_jar = home .. "/.local/share/nvim/mason/share/jdtls/plugins/org.eclipse.equinox.launcher.jar"
      --
      --jdtls.setup({
        --cmd = {
          --'java',
          --'-Declipse.application=org.eclipse.jdt.ls.core.id1',
          --'-Dosgi.bundles.defaultStartLevel=4',
          --'-Declipse.product=org.eclipse.jdt.ls.core.product',
          --'-Dlog.protocol=true',
          --'-Dlog.level=ALL',
          --'-javaagent:' .. lombok_path,
          --'-Xms1g',
          --'--add-modules=ALL-SYSTEM',
          --'--add-opens',
          --'java.base/java.util=ALL-UNNAMED',
          --'--add-opens',
          --'java.base/java.lang=ALL-UNNAMED',
          --'-jar', equinox_jar,
          --'-configuration', home .. '/.local/share/nvim/mason/packages/jdtls/config_linux',
          --'-data', home .. '/workspace'
        --},
        --root_dir = require('lspconfig').util.root_pattern('.git', 'mvnw', 'gradlew')
      --})
    --end
  }

